-- Enhancements for interaction_log table to include detailed agent processing steps

-- Add new columns to interaction_log, ensuring they are nullable as they
-- will only be populated for interactions that involve detailed agent processing
-- and successful filter calls.

ALTER TABLE interaction_log
ADD COLUMN IF NOT EXISTS kb_article_slug TEXT NULL,
ADD COLUMN IF NOT EXISTS pre_filter_response TEXT NULL,
ADD COLUMN IF NOT EXISTS pre_filter_confidence REAL NULL,
ADD COLUMN IF NOT EXISTS filter_alignment_score REAL NULL,
ADD COLUMN IF NOT EXISTS filter_warnings TEXT[] NULL; -- PostgreSQL array for warnings

COMMENT ON COLUMN interaction_log.kb_article_slug IS 'Slug of the knowledge base article matched by the agent.';
COMMENT ON COLUMN interaction_log.pre_filter_response IS 'The raw response generated by the agent before passing through the Resonator Filter.';
COMMENT ON COLUMN interaction_log.pre_filter_confidence IS 'The agent''s confidence score before Resonator Filter adjustments.';
COMMENT ON COLUMN interaction_log.filter_alignment_score IS 'The alignment score returned by the Resonator Filter.';
COMMENT ON COLUMN interaction_log.filter_warnings IS 'Any warnings returned by the Resonator Filter.';

```
